### ISSUE TITLE
Manage  multi-gtfs

### ISSUE THREAD

**Issue by francot** [OpenTransitTools/gtfsdb#16]
Possibility to import and manage multi gtfs keeping track of historical data.
Add an import_id in the model's primary keys.

**Comment by fpurcell** [comment]
Hey francot.  Thanks for the interest in gtfsdb.  I have a possible solution to what you're asking by way of database schema manipulation (see below).  Because of the added complexity in adding an import_id primary key to pretty much to every table and every query, I don't feel this would be the correct solution for gtfsdb.  So I'm going to close this issue.  But I'm happy to discuss further...

The solution to your problem of maintaining a history of gtfs data may be solved with the use of a db that supports multiple schemas (e.g., postgres, oracle, etc...).  You could load new gtfs data into differently named schemas based on import_id (or better ... use feed_info.txt/feed_version as that schema name).  For example, I use multiple schemas to load GTFS data from multiple different agencies into the same database.  From there, I can make queries of all the data in the different schemas via a where clause (not a great query below, but a decent example):

select *
from "C-TRAN".stops cs, "TRIMET".stops ts
where st_distance(cs.geom, ts.geom) < 0.001
