### ISSUE TITLE
gtfsdb-load overwrites existing data

### ISSUE THREAD

**Issue by mbattifarano** [OpenTransitTools/gtfsdb#8]
I'm trying to build a database with information from multiple gtfs feeds around the US. gtfsdb does a great job of representing the data in postgres, but overwrites existing data. Is there any way to change this?

**Comment by fpurcell** [comment]
To store data from different gtfs feeds simultaneously, the only solution supported today is to use a different database schema to store each feed.

Upside to this is simplicity (e.g., don't have to worry about having id/data clashes where multiple feeds use the same ids, or where two different feeds from the same provider have date based data that overlaps/conflicts in some way).  This approach works great if you're just loading data with gtfsdb, and then using some other tool to query / manipulate the data.  Of course you need a db that supports schemas (postgres == yes, sqlite == no), so that's a slight downside.  Other minor downside is the schema must first exist in postgres before you attempt to load the data via gtfsdb.

The real downside to multiple schemas comes if you want to later query your loaded data via the gtfsdb model objects within a single process.  If that's the case (say a webapp that shows multiple feeds), you'll need to instantiate a set of gtfsdb model objects for each of the different schemas in your multi-feed database.  In theory, this should work and it's more a programming task of juggling multiple instances of gtfsdb model objects.  But this has only been minimally tested on my end ... so if you go the multi-schema route, and run into any gotchas, open a ticket to let Mike and me know...
